name: compile-qt5-plugin
run-name: ${{ github.actor }} Build and Release VirtualPad plugin (Linux + Qt 5.12.8)
on: [push]
jobs:
  build-and-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
      - uses: actions/checkout@v3
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
            version: '5.12.8'
            host: 'linux'
            target: 'desktop'
            dir: '${{ github.workspace }}/'
      - name: Build #1
        run: qmake virtualpadplugin.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
      - name: Build #2
        run: make -f Makefile qmake_all
      - name: Build #3
        run: make -j8
      - name: Archive plugin
        uses: actions/upload-artifact@v3
        with:
          name: qt5-plugin
          path: libvirtualpadplugin.so 
